spring.application.name=RecetasAPI-SpringBoot

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/recetasapi
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update


server.port=8080

# habilitar/deshabilitar api-docs - swagger-ui
springdoc.api-docs.enabled = true
springdoc.swagger-ui.enabled=true

# definir la ruta de swagger-ui
springdoc.swagger-ui.path=/doc/swagger-ui.html


